### ISSUE TITLE
Highlighting ES6 file results in stray <span> elements

### ISSUE THREAD

**Issue by heisian** [felixfbecker/cli-highlight#7]
Cmd:
`$ highlight S3.js`

Output:
```node
// S3/index.js
// -----------
// Module for securely storing, retrieving, and deleting objects on S3.
import https        from 'https';
import S3SDK        from 'aws-sdk/clients/s3';
import { log }      from 'shared/log';
import APIInterface from 'shared/server/_lib/APIInterface';
import { uuid }     from 'shared/utilities';

export default <span class="hljs-class">class S3 extends APIInterface </span>{
  get requiredConfigKeys() {
    return ['bucket', 'endpoint', 'accessKeyId', 'secretAccessKey'];
  }

  constructor({ bucket, endpoint, accessKeyId, secretAccessKey } = {
    bucket: process.env.AWS_S3_BUCKET,
    endpoint: process.env.AWS_S3_ENDPOINT,
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
  }, createDuplicate = false) {
    const defaults = {
      region: 'us-east-1',
      sslEnabled: true,
      httpOptions: { agent: new https.Agent() },
      apiVersion: '2006-03-01',
    };
    super(Object.assign(defaults, { bucket, endpoint, accessKeyId, secretAccessKey }), false, createDuplicate);
  }
```

Perhaps this is a `highlight.js` issue?

**Comment by heisian** [comment]
Thanks! It is almost solved, but this error gets thrown:
```
11:26 $ highlight S3.js 
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/Users/timothyhuang/.config/yarn/global/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/Users/timothyhuang/.config/yarn/global/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (native)
    at argsert (/Users/timothyhuang/.config/yarn/global/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/Users/timothyhuang/.config/yarn/global/node_modules/yargs/yargs.js:757:5)
    at Object.<anonymous> (/Users/timothyhuang/.config/yarn/global/node_modules/cli-highlight/dist/cli.js:20:6)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

**However**, the proceeding output of `S3.js` is correct and looks great.

**Comment by felixfbecker** [comment]
Thanks! Should be fixed in https://github.com/felixfbecker/cli-highlight/commit/41d3734efade3078848e5480fb7dc0eecef93034

**Comment by heisian** [comment]
awesome, you rock

**Comment by felixfbecker** [comment]
🎸
